/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChargersRouteImport } from './routes/chargers'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EliteIndexRouteImport } from './routes/elite.index'
import { Route as SolutionsProjectReportRouteImport } from './routes/solutions.project-report'
import { Route as SolutionsPostInstallationInspectionRouteImport } from './routes/solutions.post-installation-inspection'
import { Route as SolutionsLandSurveyRouteImport } from './routes/solutions.land-survey'
import { Route as SolutionsInstallationRouteImport } from './routes/solutions.installation'
import { Route as SolutionsBusinessConsultancyRouteImport } from './routes/solutions.business-consultancy'
import { Route as ModelsFofoRouteImport } from './routes/models.fofo'
import { Route as ModelsFocoRouteImport } from './routes/models.foco'
import { Route as ModelsCocoRouteImport } from './routes/models.coco'
import { Route as ModelsCapitalCircleRouteImport } from './routes/models.capital-circle'
import { Route as EliteSettingsRouteImport } from './routes/elite.settings'
import { Route as EliteProjectsRouteImport } from './routes/elite.projects'
import { Route as ElitePartnersRouteImport } from './routes/elite.partners'
import { Route as EliteMarketplaceRouteImport } from './routes/elite.marketplace'
import { Route as EliteLandRouteImport } from './routes/elite.land'
import { Route as EliteInvestorsRouteImport } from './routes/elite.investors'
import { Route as EliteFundingRouteImport } from './routes/elite.funding'
import { Route as EliteDocumentsRouteImport } from './routes/elite.documents'
import { Route as EliteDashboardRouteImport } from './routes/elite.dashboard'
import { Route as EliteCommunityRouteImport } from './routes/elite.community'
import { Route as EliteAiRouteImport } from './routes/elite.ai'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargersRoute = ChargersRouteImport.update({
  id: '/chargers',
  path: '/chargers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteIndexRoute = EliteIndexRouteImport.update({
  id: '/elite/',
  path: '/elite/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsProjectReportRoute = SolutionsProjectReportRouteImport.update({
  id: '/solutions/project-report',
  path: '/solutions/project-report',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsPostInstallationInspectionRoute =
  SolutionsPostInstallationInspectionRouteImport.update({
    id: '/solutions/post-installation-inspection',
    path: '/solutions/post-installation-inspection',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsLandSurveyRoute = SolutionsLandSurveyRouteImport.update({
  id: '/solutions/land-survey',
  path: '/solutions/land-survey',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsInstallationRoute = SolutionsInstallationRouteImport.update({
  id: '/solutions/installation',
  path: '/solutions/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsBusinessConsultancyRoute =
  SolutionsBusinessConsultancyRouteImport.update({
    id: '/solutions/business-consultancy',
    path: '/solutions/business-consultancy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModelsFofoRoute = ModelsFofoRouteImport.update({
  id: '/models/fofo',
  path: '/models/fofo',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsFocoRoute = ModelsFocoRouteImport.update({
  id: '/models/foco',
  path: '/models/foco',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsCocoRoute = ModelsCocoRouteImport.update({
  id: '/models/coco',
  path: '/models/coco',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsCapitalCircleRoute = ModelsCapitalCircleRouteImport.update({
  id: '/models/capital-circle',
  path: '/models/capital-circle',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteSettingsRoute = EliteSettingsRouteImport.update({
  id: '/elite/settings',
  path: '/elite/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteProjectsRoute = EliteProjectsRouteImport.update({
  id: '/elite/projects',
  path: '/elite/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ElitePartnersRoute = ElitePartnersRouteImport.update({
  id: '/elite/partners',
  path: '/elite/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteMarketplaceRoute = EliteMarketplaceRouteImport.update({
  id: '/elite/marketplace',
  path: '/elite/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteLandRoute = EliteLandRouteImport.update({
  id: '/elite/land',
  path: '/elite/land',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteInvestorsRoute = EliteInvestorsRouteImport.update({
  id: '/elite/investors',
  path: '/elite/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteFundingRoute = EliteFundingRouteImport.update({
  id: '/elite/funding',
  path: '/elite/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteDocumentsRoute = EliteDocumentsRouteImport.update({
  id: '/elite/documents',
  path: '/elite/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteDashboardRoute = EliteDashboardRouteImport.update({
  id: '/elite/dashboard',
  path: '/elite/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteCommunityRoute = EliteCommunityRouteImport.update({
  id: '/elite/community',
  path: '/elite/community',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteAiRoute = EliteAiRouteImport.update({
  id: '/elite/ai',
  path: '/elite/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/chargers': typeof ChargersRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/elite/ai': typeof EliteAiRoute
  '/elite/community': typeof EliteCommunityRoute
  '/elite/dashboard': typeof EliteDashboardRoute
  '/elite/documents': typeof EliteDocumentsRoute
  '/elite/funding': typeof EliteFundingRoute
  '/elite/investors': typeof EliteInvestorsRoute
  '/elite/land': typeof EliteLandRoute
  '/elite/marketplace': typeof EliteMarketplaceRoute
  '/elite/partners': typeof ElitePartnersRoute
  '/elite/projects': typeof EliteProjectsRoute
  '/elite/settings': typeof EliteSettingsRoute
  '/models/capital-circle': typeof ModelsCapitalCircleRoute
  '/models/coco': typeof ModelsCocoRoute
  '/models/foco': typeof ModelsFocoRoute
  '/models/fofo': typeof ModelsFofoRoute
  '/solutions/business-consultancy': typeof SolutionsBusinessConsultancyRoute
  '/solutions/installation': typeof SolutionsInstallationRoute
  '/solutions/land-survey': typeof SolutionsLandSurveyRoute
  '/solutions/post-installation-inspection': typeof SolutionsPostInstallationInspectionRoute
  '/solutions/project-report': typeof SolutionsProjectReportRoute
  '/elite/': typeof EliteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/chargers': typeof ChargersRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/elite/ai': typeof EliteAiRoute
  '/elite/community': typeof EliteCommunityRoute
  '/elite/dashboard': typeof EliteDashboardRoute
  '/elite/documents': typeof EliteDocumentsRoute
  '/elite/funding': typeof EliteFundingRoute
  '/elite/investors': typeof EliteInvestorsRoute
  '/elite/land': typeof EliteLandRoute
  '/elite/marketplace': typeof EliteMarketplaceRoute
  '/elite/partners': typeof ElitePartnersRoute
  '/elite/projects': typeof EliteProjectsRoute
  '/elite/settings': typeof EliteSettingsRoute
  '/models/capital-circle': typeof ModelsCapitalCircleRoute
  '/models/coco': typeof ModelsCocoRoute
  '/models/foco': typeof ModelsFocoRoute
  '/models/fofo': typeof ModelsFofoRoute
  '/solutions/business-consultancy': typeof SolutionsBusinessConsultancyRoute
  '/solutions/installation': typeof SolutionsInstallationRoute
  '/solutions/land-survey': typeof SolutionsLandSurveyRoute
  '/solutions/post-installation-inspection': typeof SolutionsPostInstallationInspectionRoute
  '/solutions/project-report': typeof SolutionsProjectReportRoute
  '/elite': typeof EliteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/chargers': typeof ChargersRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/elite/ai': typeof EliteAiRoute
  '/elite/community': typeof EliteCommunityRoute
  '/elite/dashboard': typeof EliteDashboardRoute
  '/elite/documents': typeof EliteDocumentsRoute
  '/elite/funding': typeof EliteFundingRoute
  '/elite/investors': typeof EliteInvestorsRoute
  '/elite/land': typeof EliteLandRoute
  '/elite/marketplace': typeof EliteMarketplaceRoute
  '/elite/partners': typeof ElitePartnersRoute
  '/elite/projects': typeof EliteProjectsRoute
  '/elite/settings': typeof EliteSettingsRoute
  '/models/capital-circle': typeof ModelsCapitalCircleRoute
  '/models/coco': typeof ModelsCocoRoute
  '/models/foco': typeof ModelsFocoRoute
  '/models/fofo': typeof ModelsFofoRoute
  '/solutions/business-consultancy': typeof SolutionsBusinessConsultancyRoute
  '/solutions/installation': typeof SolutionsInstallationRoute
  '/solutions/land-survey': typeof SolutionsLandSurveyRoute
  '/solutions/post-installation-inspection': typeof SolutionsPostInstallationInspectionRoute
  '/solutions/project-report': typeof SolutionsProjectReportRoute
  '/elite/': typeof EliteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/blog'
    | '/calculator'
    | '/chargers'
    | '/contact'
    | '/franchise'
    | '/blog/$slug'
    | '/elite/ai'
    | '/elite/community'
    | '/elite/dashboard'
    | '/elite/documents'
    | '/elite/funding'
    | '/elite/investors'
    | '/elite/land'
    | '/elite/marketplace'
    | '/elite/partners'
    | '/elite/projects'
    | '/elite/settings'
    | '/models/capital-circle'
    | '/models/coco'
    | '/models/foco'
    | '/models/fofo'
    | '/solutions/business-consultancy'
    | '/solutions/installation'
    | '/solutions/land-survey'
    | '/solutions/post-installation-inspection'
    | '/solutions/project-report'
    | '/elite/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/blog'
    | '/calculator'
    | '/chargers'
    | '/contact'
    | '/franchise'
    | '/blog/$slug'
    | '/elite/ai'
    | '/elite/community'
    | '/elite/dashboard'
    | '/elite/documents'
    | '/elite/funding'
    | '/elite/investors'
    | '/elite/land'
    | '/elite/marketplace'
    | '/elite/partners'
    | '/elite/projects'
    | '/elite/settings'
    | '/models/capital-circle'
    | '/models/coco'
    | '/models/foco'
    | '/models/fofo'
    | '/solutions/business-consultancy'
    | '/solutions/installation'
    | '/solutions/land-survey'
    | '/solutions/post-installation-inspection'
    | '/solutions/project-report'
    | '/elite'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/blog'
    | '/calculator'
    | '/chargers'
    | '/contact'
    | '/franchise'
    | '/blog/$slug'
    | '/elite/ai'
    | '/elite/community'
    | '/elite/dashboard'
    | '/elite/documents'
    | '/elite/funding'
    | '/elite/investors'
    | '/elite/land'
    | '/elite/marketplace'
    | '/elite/partners'
    | '/elite/projects'
    | '/elite/settings'
    | '/models/capital-circle'
    | '/models/coco'
    | '/models/foco'
    | '/models/fofo'
    | '/solutions/business-consultancy'
    | '/solutions/installation'
    | '/solutions/land-survey'
    | '/solutions/post-installation-inspection'
    | '/solutions/project-report'
    | '/elite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  ChargersRoute: typeof ChargersRoute
  ContactRoute: typeof ContactRoute
  FranchiseRoute: typeof FranchiseRoute
  EliteAiRoute: typeof EliteAiRoute
  EliteCommunityRoute: typeof EliteCommunityRoute
  EliteDashboardRoute: typeof EliteDashboardRoute
  EliteDocumentsRoute: typeof EliteDocumentsRoute
  EliteFundingRoute: typeof EliteFundingRoute
  EliteInvestorsRoute: typeof EliteInvestorsRoute
  EliteLandRoute: typeof EliteLandRoute
  EliteMarketplaceRoute: typeof EliteMarketplaceRoute
  ElitePartnersRoute: typeof ElitePartnersRoute
  EliteProjectsRoute: typeof EliteProjectsRoute
  EliteSettingsRoute: typeof EliteSettingsRoute
  ModelsCapitalCircleRoute: typeof ModelsCapitalCircleRoute
  ModelsCocoRoute: typeof ModelsCocoRoute
  ModelsFocoRoute: typeof ModelsFocoRoute
  ModelsFofoRoute: typeof ModelsFofoRoute
  SolutionsBusinessConsultancyRoute: typeof SolutionsBusinessConsultancyRoute
  SolutionsInstallationRoute: typeof SolutionsInstallationRoute
  SolutionsLandSurveyRoute: typeof SolutionsLandSurveyRoute
  SolutionsPostInstallationInspectionRoute: typeof SolutionsPostInstallationInspectionRoute
  SolutionsProjectReportRoute: typeof SolutionsProjectReportRoute
  EliteIndexRoute: typeof EliteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chargers': {
      id: '/chargers'
      path: '/chargers'
      fullPath: '/chargers'
      preLoaderRoute: typeof ChargersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/': {
      id: '/elite/'
      path: '/elite'
      fullPath: '/elite/'
      preLoaderRoute: typeof EliteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/project-report': {
      id: '/solutions/project-report'
      path: '/solutions/project-report'
      fullPath: '/solutions/project-report'
      preLoaderRoute: typeof SolutionsProjectReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/post-installation-inspection': {
      id: '/solutions/post-installation-inspection'
      path: '/solutions/post-installation-inspection'
      fullPath: '/solutions/post-installation-inspection'
      preLoaderRoute: typeof SolutionsPostInstallationInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/land-survey': {
      id: '/solutions/land-survey'
      path: '/solutions/land-survey'
      fullPath: '/solutions/land-survey'
      preLoaderRoute: typeof SolutionsLandSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/installation': {
      id: '/solutions/installation'
      path: '/solutions/installation'
      fullPath: '/solutions/installation'
      preLoaderRoute: typeof SolutionsInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/business-consultancy': {
      id: '/solutions/business-consultancy'
      path: '/solutions/business-consultancy'
      fullPath: '/solutions/business-consultancy'
      preLoaderRoute: typeof SolutionsBusinessConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/fofo': {
      id: '/models/fofo'
      path: '/models/fofo'
      fullPath: '/models/fofo'
      preLoaderRoute: typeof ModelsFofoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/foco': {
      id: '/models/foco'
      path: '/models/foco'
      fullPath: '/models/foco'
      preLoaderRoute: typeof ModelsFocoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/coco': {
      id: '/models/coco'
      path: '/models/coco'
      fullPath: '/models/coco'
      preLoaderRoute: typeof ModelsCocoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/capital-circle': {
      id: '/models/capital-circle'
      path: '/models/capital-circle'
      fullPath: '/models/capital-circle'
      preLoaderRoute: typeof ModelsCapitalCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/settings': {
      id: '/elite/settings'
      path: '/elite/settings'
      fullPath: '/elite/settings'
      preLoaderRoute: typeof EliteSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/projects': {
      id: '/elite/projects'
      path: '/elite/projects'
      fullPath: '/elite/projects'
      preLoaderRoute: typeof EliteProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/partners': {
      id: '/elite/partners'
      path: '/elite/partners'
      fullPath: '/elite/partners'
      preLoaderRoute: typeof ElitePartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/marketplace': {
      id: '/elite/marketplace'
      path: '/elite/marketplace'
      fullPath: '/elite/marketplace'
      preLoaderRoute: typeof EliteMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/land': {
      id: '/elite/land'
      path: '/elite/land'
      fullPath: '/elite/land'
      preLoaderRoute: typeof EliteLandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/investors': {
      id: '/elite/investors'
      path: '/elite/investors'
      fullPath: '/elite/investors'
      preLoaderRoute: typeof EliteInvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/funding': {
      id: '/elite/funding'
      path: '/elite/funding'
      fullPath: '/elite/funding'
      preLoaderRoute: typeof EliteFundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/documents': {
      id: '/elite/documents'
      path: '/elite/documents'
      fullPath: '/elite/documents'
      preLoaderRoute: typeof EliteDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/dashboard': {
      id: '/elite/dashboard'
      path: '/elite/dashboard'
      fullPath: '/elite/dashboard'
      preLoaderRoute: typeof EliteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/community': {
      id: '/elite/community'
      path: '/elite/community'
      fullPath: '/elite/community'
      preLoaderRoute: typeof EliteCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/ai': {
      id: '/elite/ai'
      path: '/elite/ai'
      fullPath: '/elite/ai'
      preLoaderRoute: typeof EliteAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BlogRoute: BlogRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  ChargersRoute: ChargersRoute,
  ContactRoute: ContactRoute,
  FranchiseRoute: FranchiseRoute,
  EliteAiRoute: EliteAiRoute,
  EliteCommunityRoute: EliteCommunityRoute,
  EliteDashboardRoute: EliteDashboardRoute,
  EliteDocumentsRoute: EliteDocumentsRoute,
  EliteFundingRoute: EliteFundingRoute,
  EliteInvestorsRoute: EliteInvestorsRoute,
  EliteLandRoute: EliteLandRoute,
  EliteMarketplaceRoute: EliteMarketplaceRoute,
  ElitePartnersRoute: ElitePartnersRoute,
  EliteProjectsRoute: EliteProjectsRoute,
  EliteSettingsRoute: EliteSettingsRoute,
  ModelsCapitalCircleRoute: ModelsCapitalCircleRoute,
  ModelsCocoRoute: ModelsCocoRoute,
  ModelsFocoRoute: ModelsFocoRoute,
  ModelsFofoRoute: ModelsFofoRoute,
  SolutionsBusinessConsultancyRoute: SolutionsBusinessConsultancyRoute,
  SolutionsInstallationRoute: SolutionsInstallationRoute,
  SolutionsLandSurveyRoute: SolutionsLandSurveyRoute,
  SolutionsPostInstallationInspectionRoute:
    SolutionsPostInstallationInspectionRoute,
  SolutionsProjectReportRoute: SolutionsProjectReportRoute,
  EliteIndexRoute: EliteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
